namespace SourceGenerators.Utils.NonSemantic {
    using System.Text;

    public static class StringBuilderExtensions {
        public static StringBuilder AppendIndent(this StringBuilder sb, IndentSource indentSource) {
            sb.Append(' ', indentSource.value);
            return sb;
        }
        
        public static StringBuilder AppendAutoGeneratedComment(this StringBuilder sb) {
            sb.AppendLine("// <auto-generated />");
            return sb;
        }
        
        public static StringBuilder AppendPragmaWarningDisable(this StringBuilder sb) {
            sb.AppendLine("#pragma warning disable");
            return sb;
        }
        
        public static StringBuilder AppendPragmaWarningRestore(this StringBuilder sb) {
            sb.AppendLine("#pragma warning restore");
            return sb;
        }
    }
}